# -*- coding: utf-8 -*-
"""suz exercice_boucles.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lW1oqyqkfYEgPp5Eaydo42ei5efS5nyJ

# Exercices — Boucles Python

**Contexte :** Tu travailles comme DA junior pour **RestoClic**, une application de commande en ligne pour restaurants. Tu dois écrire des scripts pour automatiser des traitements sur les données de commandes.

Trois niveaux progressifs :
- **Niveau 1 — Guidé** : la structure est là, tu complètes les parties manquantes
- **Niveau 2 — Semi-guidé** : le contexte est donné, tu écris le code
- **Niveau 3 — Autonome** : un énoncé en français, tu fais tout
- **Bonus** : pour les plus rapides

## Niveau 1 — Guidé

### Exercice 1 — Compteur de livraisons

RestoClic a reçu 8 commandes à traiter. Complète la boucle `while` pour afficher le numéro de chaque livraison, de 1 à 8.

Résultat attendu :
```
Livraison n°1 en cours...
Livraison n°2 en cours...
...
Livraison n°8 en cours...
Toutes les livraisons sont parties !
```
"""

numero_livraison = 1
total_livraisons = 8

while numero_livraison <= total_livraisons:
    print(f"Livraison n°{numero_livraison} en cours...")
    numero_livraison += 1

print("Toutes les livraisons sont parties !")

"""### Exercice 2 — Afficher le menu

Complète la boucle `for` pour afficher chaque plat du menu.

Résultat attendu :
```
Pizza Margherita
Burger Classic
Salade César
Tiramisu
```

"""

menu = ["Pizza Margherita", "Burger Classic", "Salade César", "Tiramisu"]

for plat in menu:
    print("miam", plat)

menu = ["Pizza Margherita", "Burger Classic", "Salade César", "Tiramisu"]

for plat in menu:
    print("miam", "salade césar")

menu = ["Pizza Margherita", "Burger Classic", "Salade César", "Tiramisu"]

for plat in menu:
    print("miam", "Burger Classic")

"""### Exercice 3 — Total des ventes

Complète la boucle pour calculer le total des ventes de la journée.

Résultat attendu : `Total des ventes : 89.5 €`

"""

ventes = [12.5, 18.0, 9.0, 22.0, 8.5, 19.5]
total = 0

for montant in ventes:
 total += montant
print(f"Total des ventes : {total} €")

"""## Niveau 2 — Semi-guidé

### Exercice 4 — Rapport de stock

RestoClic doit afficher un rapport de stock pour chaque ingrédient. Pour chaque ingrédient :
- Si le stock est **supérieur à 20** : afficher `"- [nom] : [stock] unités"`
- Si le stock est **entre 5 et 20 inclus** : afficher `"Attention : [nom] : stock faible ([stock] unités)"`
- Si le stock est **inférieur à 5** : afficher `"- [nom] : RUPTURE IMMINENTE"`

> 💡 **Tip :** chaque `ingredient` est un couple `(nom, stock)`. Pour récupérer ses deux éléments, utilise des crochets avec un indice qui commence à **0** : `ingredient[0]` donne le premier élément (le nom), `ingredient[1]` donne le second (le stock).
> ```python
> exemple = ("Farine", 45)
> print(exemple[0])   # "Farine"
> print(exemple[1])   # 45
> ```
"""

ingredients = [
    ("Farine", 45),
    ("Tomates", 12),
    ("Mozzarella", 3),
    ("Basilic", 28),
    ("Huile d'olive", 7)
]

for ingredient in ingredients:
    nom = ingredient[0]
    stock = ingredient[1]

    if stock > 20:
        print("-", nom, ":", stock, "unités")
    elif 5 <= stock <= 20:
        print("Attention :", nom, ":", stock, "unités")
    else:
        print("-", nom, ": RUPTURE IMMINENTE")

"""### Exercice 5 — Première commande au-dessus du seuil

RestoClic veut trouver la **première** commande dont le montant dépasse 25 €.
Dès que tu la trouves, affiche son montant et arrête-toi.

Résultat attendu : `Première commande > 25 € : 31.0 €`

"""

commandes = [12.5, 18.0, 9.0, 31.0, 22.0, 42.5, 8.5]

for c in commandes:
    if c > 25:
        print(f"Première commande > 25 € : {c} €")
        break

"""### Exercice 6 — Filtrer les données manquantes

Certaines commandes ont un montant à `-1` (donnée manquante ou erreur de saisie). Calcule le total **uniquement sur les commandes valides** (montant > 0). Affiche aussi le nombre de commandes ignorées.

"""

commandes_brutes = [12.5, -1, 18.0, -1, 9.0, 22.0, -1, 8.5]

total = 0
ignore = 0

for c in commandes_brutes:
    if c <= 0:
        ignore += 1
        continue
    total += c

print("Total :", total)
print("Commandes ignorées :", ignore)

"""## Niveau 3 — Autonome

### Exercice 7 — Rapport journalier

À partir de la liste de ventes ci-dessous, écris un script qui affiche :
1. Le nombre total de ventes
2. Le montant total
3. La vente la plus haute
4. La vente la plus basse
5. La moyenne (arrondie à 2 décimales)

N'utilise pas de fonctions Python comme `max()`, `min()` ou `sum()` — calcule tout avec une boucle.
"""

ventes = [12.5, 18.0, 9.0, 31.0, 22.0, 42.5, 8.5, 15.0, 27.5]

total = 0
compteur = 0

max_v = ventes[0]
min_v = ventes[0]

for v in ventes:
    total += v
    compteur += 1

    if v > max_v:
        max_v = v
    if v < min_v:
        min_v = v

moyenne = round(total / compteur, 2)

print("Nombre total de ventes :", compteur)
print("Total :", total)
print("Plus haute :", max_v)
print("Plus basse :", min_v)
print("Moyenne :", moyenne)

"""### Exercice 8 — Table de multiplicateurs de prix

RestoClic applique des majorations la nuit (entre 22h et 6h). Génère et affiche la table des prix majorés pour des taux de majoration allant de 5% à 30% (par pas de 5%), sur un prix de base de 15 €.

Résultat attendu :
```
Majoration 5% -> 15.75 €
Majoration 10% -> 16.50 €
...
Majoration 30% -> 19.50 €
```

"""

prix_base = 15.0

for taux in range(5, 31, 5):
    prix = prix_base * (1 + taux / 100)
    print(f"Majoration {taux}% -> {prix:.2f} €")

"""## Bonus

### Bonus — FizzBuzz version DA

Pour chaque commande numérotée de 1 à 20 :
- Si le numéro est divisible par **3** -> afficher `"Commande groupée"`
- Si le numéro est divisible par **5** -> afficher `"Commande express"`
- Si divisible par **3 ET 5** -> afficher `"Commande prioritaire"`
- Sinon -> afficher `"Commande n°X"`
"""

for i in range(1, 21):
    if i % 3 == 0 and i % 5 == 0:
        print("Commande prioritaire")
    elif i % 3 == 0:
        print("Commande groupée")
    elif i % 5 == 0:
        print("Commande express")
    else:
        print(f"Commande n°{i}")